version: "3.3"

services:
    mongo:
        image: mongo
        deploy:
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role == manager]
        volumes:
            - /data/db:/data/db
        networks:
            - net
        ports:
            - "27017:27017"

networks:
    net:
       driver: overlay

