version: "3.3"

services:

  mongo:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGODB_USER=euclid 
      - MONGODB_PASS=12345
    volumes:
      - mongodata:/data/db
    network_mode: "host"
#    networks:
#      - net
    ports:
      - "27017:27017"

volumes:
  mongodata:
    driver: local

#networks:
#  net:
#    driver: overlay
